name: Version Check

on:
  schedule:
    - cron: '0 05 * * 0'
  workflow_dispatch:

jobs:
  test:
    name: Version Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      # version check is intentionally not pinned (self reference testing the main branch)
      - name: Version Check
        uses: docker://ghcr.io/sudo-bmitch/version-bump:edge
        with:
          args: check
