name: Vulnerability Check

on:
  schedule:
    - cron: '0 06 * * 0' # 6am UTC on Sundays
  workflow_dispatch:

jobs:
  govunlcheck:
    name: Go Vuln Check
    runs-on: ubuntu-latest
    env:
      RELEASE_GO_VER: "1.21"

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: "Set up Go"
      uses: actions/setup-go@v5
      with:
        go-version: "${{ env.RELEASE_GO_VER }}"
        check-latest: true

    - name: "Install govulncheck"
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: "Run govulncheck"
      run: |
        govulncheck ./...

    - name: "Install OSV Scanner"
      run: |
        go install github.com/google/osv-scanner/cmd/osv-scanner@latest

    - name: "Run OSV Scanner"
      run: |
        osv-scanner -r .
